name: auto_buy
description: AUTO_BUY

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  provider: ^5.0.0
  cloud_firestore: ^1.0.3
  flutter_svg: ^0.21.0+1
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
  image_picker: ^0.7.5+3
  http: ^0.13.3
  flutter_spinkit:
  flutter_card_swipper: ^0.4.0
  photo_view: ^0.11.1
  firebase_storage: ^8.0.6
  path_provider: ^2.0.1
  cached_network_image: ^3.0.0
  material_floating_search_bar: ^0.2.6
  image_cropper: ^1.4.0
  shared_preferences: ^2.0.5
  commons:
<<<<<<< Updated upstream
=======
  charts_flutter: ^0.10.0
  connectivity: ^3.0.6
  google_speech: ^2.0.1
  flutter_sound: ^8.1.9
  permission_handler: ^8.1.2
>>>>>>> Stashed changes


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/optioface.png
    - assets/images/optiologo.png
    - assets/images/optiologo.svg
    - assets/images/google-logo.png
    - assets/images/facebook-logo.png
    - assets/images/Optio_body_happy.svg
    - assets/images/optioface.svg
    - assets/images/optiobodyhi.svg
    - assets/gifs/loading_2.gif
    - assets/images/Tony.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
